[versions]
# core
kotlin = "1.9.22"
androidGradlePlugin = "8.2.2"
# ksp
ksp = "1.9.22-1.0.17"
# compose
composeBom = "2024.02.00"
activityCompose = "1.8.2"
# ktor
ktor = "2.3.7"
# hilt
hilt = "2.48"
hiltNavigationComposeVersion = "1.1.0"
#hiltCompilerVersion = "1.0.0"

# testing
junit = "4.13.2"
testExtJunit = "1.1.5"
espressoCore = "3.5.1"

[libraries]
# compose
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-ui = { module = "androidx.compose.ui:ui" }
androidx-material3 = { module = "androidx.compose.material3:material3" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
androidx-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
androidx-compose-foundation = { group = "androidx.compose.foundation", name = "foundation" }

#ktor
ktorCore = { module = "io.ktor:ktor-client-core", version.ref = "ktor"}
ktorSerialization = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor"}
ktorSerializationJson = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor"}
ktorAndroid = { module = "io.ktor:ktor-client-android", version.ref = "ktor"}

#hilt
hiltAndroid = { module = "com.google.dagger:hilt-android", version.ref = "hilt"}
hiltAndroidCompiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt"}
#hiltCompiler = { module = "androidx.hilt:hilt-compiler", version.ref = "hilt"}
hiltAgp = { module = "com.google.dagger:hilt-android-gradle-plugin", version.ref = "hilt"}
hiltNavigationCompose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hiltNavigationComposeVersion"}

# testing
junit = { group = "junit", name = "junit", version.ref = "junit" }
test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "testExtJunit" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }

[plugins]
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
hilt-gradle-plugin = { id = "com.google.dagger", version.ref = "hilt" }

[bundles]
compose = [
    "androidx-activity-compose",
    "androidx-ui",
    "androidx-material3",
    "androidx-ui-graphics",
    "androidx-ui-tooling",
    "androidx-ui-tooling-preview",
    "androidx-compose-foundation"
]
ktor = [
    "ktorCore",
    "ktorSerialization",
    "ktorSerializationJson",
    "ktorAndroid"
]
testing = [
    "junit",
    "test-ext-junit",
    "espresso-core",
]